server:
  port:
    8083
spring:
  application:
    name: "inventoryservice"
  datasource:
    url: jdbc:mysql://localhost:3308/inventory
    username: root
    password: mysql
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
