server:
  port:
    8082

spring:
  application:
    name: "productservice"
  data:
    mongodb:
      uri: "mongodb://admin:mongodb@localhost:27017/products"
      database: "products"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "productservice"
    description: "Product Service - Grab Goods - Retail Microservices System"
    version: "1.0.0"