server:
  port:
    8085

spring:
  application:
    name: "cartservice"
  data:
    mongodb:
      uri: "mongodb://admin:mongodb@localhost:27018/cart"
      database: "cart"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"